### ISSUE TITLE
[bug] RandomGenerateコンポーネントの最初のロード時にAPIがエラーになる。

### ISSUE THREAD

**Issue by orchid69** [cc-teleto/teleto-frontend#15]
# 事象
メンバーを追加して、開始ボタンを押下後API(GET)エラーが出ている。
```
RandomGenerate.jsx:10 GET https://ttnxcty7yc.execute-api.us-east-2.amazonaws.com/stage/members/?random=true&grouphash= 402
```

# 考えられる原因
直接的な原因はgrouphashが空のままAPIを投げているからだと思われる。

# 修正案
1. 初回RandomGenerateのrender時はgrouphashが返却されるまで待つ。
2. 初回RandomGenerate時はrenderは行うがapiのrequestはgrouphashが返却されるまで待つ。
2. grouphashが空の場合はAPIを送らない。

非同期処理をフル活用するなら2が良さそう？

**Comment by krkettle** [comment]
2の方針でsetStateを待てるように修正します

**Comment by regent0ro** [comment]
useRefを利用して、初回はfetchを実行しないように修正
参考：https://qiita.com/nishiurahiroki/items/7e9aa809abc655378682
